### ISSUE TITLE
kinit: Cannot contact any KDC for realm '42.FR' while getting initial credentials

### ISSUE THREAD

**Issue by marc3825** [colundrum/42_vogsphere_access#1]
% kinit *user*
kinit: Cannot contact any KDC for realm '42.FR' while getting initial credentials

krb5 version: 1.13.2
openssh version: 7.1p1
libssh2 version: 1.6.0
uname -ros: Linux 4.3.0-1-ck GNU/Linux

cat /etc/ssh/ssh_config
Host *.42.fr
     SendEnv LANG LC_*
     StrictHostKeyChecking no
     GSSAPIAuthentication yes 
     GSSAPIDelegateCredentials yes 
     PasswordAuthentication yes

cat ~/.ssh/config
Host vgs vgs.42.fr vgse vgse.42.fr vogsphere vogsphere.42.fr vogsphere-exam vogsphere-exam.42.fr
        User vogsphere

cat /etc/krb5.conf
[logging]
        kdc = CONSOLE

[libdefaults]
        default_realm = 42.FR
        forwardable = true
        proxiable = true
        dns_lookup_kdc = true
        dns_lookup_realm = true
        allow_weak_crypto = true

[realms]
        42.FR = {
                kdc = kdc1.42.fr
                kdc = kdc2.42.fr
                admin_server = kdc1.42.fr
                default_domain = 42.fr
                default_lifetime = 7d
                ticket_lifetime = 7d
        }
        STAFF.42.FR = {
                kdc = dc1.staff.42.fr
                admin_server = dc1.staff.42.fr
                default_domain = staff.42.fr
        }

[domain_realm]
        .42.fr = 42.FR
        42.fr = 42.FR
        .staff.42.fr = STAFF.42.FR
        staff.42.fr = STAFF.42.FR

**Comment by colundrum** [comment]
Bonjour !

Alors, je pense que j'avais été suffisamment clair dans le README.md mais ce n'est peut-être pas le cas.

    anywhere in 42's school

J'ai retesté à l'instant et tout est ok.

Petite capture de ma connexion wifi :

![connection](https://cloud.githubusercontent.com/assets/5010785/11423451/c418f0ae-9444-11e5-9eed-cd8410616fdf.png)

Donc si tu es n'importe où et connecté au réseau de 42, ça roule.

Donc aucun bug, juste une mauvaise lecture du README.md.

Nota : un rapport de bug sur github, c'est pas le forum de l'intra !
