### ISSUE TITLE
Bug using 42's wifi

### ISSUE THREAD

**Issue by colundrum** [colundrum/42_vogsphere_access#2]
I know about this bug and I work on a solution for wifi connection.

## Reason of this bug :
- 42's wifi network doesn't permit the access to KDC (for kerberos) and SSH (for vogsphere)

# This is working when you're connected by ethernet.

![Freedom - Martin Luther King, Jr.](http://www.newerapolitics.org/uploads/1/3/2/0/13202651/5603539_orig.jpg)

**Comment by colundrum** [comment]
News about kinit && git clone :
- OK with 42
- FAIL with 42 Event

**Comment by colundrum** [comment]
solved but keep closed source

**Comment by franklinexpress** [comment]
How do I get it working in the USA piscine? I tried but doesn't work

**Comment by colundrum** [comment]
@franklinexpress : Not the right way, you have opened the issue #3
You need to connect to 42 and not 42 Event.
Also I lock this thread because you're doing necro-bumping.
