### ISSUE TITLE
WORK in USA?

### ISSUE THREAD

**Issue by franklinexpress** [colundrum/42_vogsphere_access#3]
Hi, I'm trying to get this to Work in the US
I changed some stuff but still getting

`krb5_cc_get_principal: No credentials cache file found`

krb5.conf

```
[libdefaults]
    default_realm = 42.US.ORG
    forwardable = true
    proxiable = true
        dns_lookup_kdc = no
        dns_lookup_realm = no
    allow_weak_crypto = true

[realms]
    42.US.ORG = {
                kdc = kdc.42.us.org
                admin_server = kdc.42.us.org
        default_domain = 42.us.org
        default_lifetime = 7d
                ticket_lifetime = 7d
    }

[domain_realm]
    .42.us.org = 42.US.ORG
    .42.us.org = 42.US.ORG
[libdefaults]
    default_realm = 42.US.ORG
    forwardable = true
    proxiable = true
        dns_lookup_kdc = no
        dns_lookup_realm = no
    allow_weak_crypto = true

[realms]
    42.US = {
                kdc = kdc1.42.us.org
                kdc = kdc2.42.us.org
                admin_server = kdc1.42.us.org
        default_domain = 42.us.org
        default_lifetime = 7d
                ticket_lifetime = 7d
    }
        STAFF.42.US = {
                kdc = dc1.staff.42.us.org
                admin_server = dc1.staff.42.us.org
                default_domain = staff.42.us.org
        }

[domain_realm]
    .42.US.ORG = 42.US.ORG
    42.US.ORG = 42.US.ORG
    .staff.42.US.ORG = STAFF.42.US.ORG
    staff.42.US.ORG = STAFF.42.US.ORG
```

**Comment by colundrum** [comment]
Hi !
I'm not at 42 US.
What is the output of `klist` ?
Can you go to an imac (in the campus) and create a gist of `/etc/krb5.conf` and `/etc/ssh/sshd_config` ?
Thanks

**Comment by franklinexpress** [comment]
[libdefaults]
    default_realm = 42.US.ORG
    forwardable = true
    proxiable = true
    dns_lookup_kdc = no
    dns_lookup_realm = no
    allow_weak_crypto = true

[realms]
    42.US.ORG = {
        kdc = kdc.42.us.org
        admin_server = kdc.42.us.org
        default_domain = 42.us.org
        default_lifetime = 7d
        ticket_lifetime = 7d
    }

[domain_realm]
    .42.us.org = 42.US.ORG
    42.us.org = 42.US.OR


klist:
--------------------------------------------------------------
Credentials cache: API:19637
        Principal: fde-los-@42.US.ORG

  Issued                Expires               Principal
Jul 25 22:36:12 2016  Jul 26 08:36:12 2016  krbtgt/42.US.ORG@42.US.ORG



sshd_config:

-----------------------------------------------------------



#     $OpenBSD: sshd_config,v 1.89 2013/02/06 00:20:42 dtucker Exp $

Port 22
ListenAddress 0.0.0.0

SyslogFacility AUTHPRIV

PermitRootLogin yes
StrictModes no

RSAAuthentication yes
PubkeyAuthentication yes

AuthorizedKeysFile      .ssh/authorized_keys

PasswordAuthentication yes
PermitEmptyPasswords no

ChallengeResponseAuthentication no

UsePrivilegeSeparation sandbox            # Default for new installations.

AcceptEnv LANG LC_*

Subsystem   sftp  /usr/libexec/sftp-server
UseDNS no
UsePAM no

AllowUsers bocal@10.42.1.0/24 bocal@10.43.1.0/24 root
AllowUsers bocal@10.51.1.6

Match User root
      RSAAuthentication yes
      PubkeyAuthentication yes
      PasswordAuthentication no
      PermitEmptyPasswords no
##      ForceCommand /sbin/yubikey_shell
#
Match User bocal
      RSAAuthentication yes
      PubkeyAuthentication yes
      PasswordAuthentication no
      PermitEmptyPasswords no

**Comment by colundrum** [comment]
Hi,
Have you tried this fork : https://github.com/hanuprateek/42_US_vogsphere_access
If it works, please tell me and I'll make this repo an hybrid installer to be used with FR and USA campus.
Have a nice day

**Comment by franklinexpress** [comment]
I'll check it out, thanks!

**Comment by franklinexpress** [comment]
kinit: krb5_get_init_creds: unable to reach any KDC in realm 42.US.ORG, tried 1 KDC

**Comment by franklinexpress** [comment]
Do I have to do it from the 42 wifi?

**Comment by colundrum** [comment]
Yes, vogsphere access is available only using ethernet or wifi in 42's building.

From the README :

> **work anywhere in 42's school, outside of clusters**
