### ISSUE TITLE
kinit: Cannot contact any KDC for realm '42.FR' while getting initial credentials

### ISSUE THREAD

**Issue by ilaliash** [colundrum/42_vogsphere_access#4]
Je rencontre telle erreur quand je me Kinit
es-ce que les domains sont changer?

**Comment by colundrum** [comment]
Bonjour !

Petites questions :
- Es-tu à 42 quand tu essaies de l'utiliser ?
- Connecter au wifi 42 et non 42 Event ou par câble ethernet ?
- Sur quel système es-tu ? Distribution GNU/Linux ? macOS ?

Peux-tu me donner la sortie des commandes suivantes :
`cat /etc/krb5.conf`
`cat /etc/ssh/ssh_config`
`cat ~/.ssh/config`

S'il le faut, on fera une session debug à 42 dans la semaine.

Have a nice day

**Comment by thumavu** [comment]
Donc, si vous n'utilisez pas l'épouse et que vous utilisez votre propre réseau, comment peut-on résoudre le problème? Cela signifie-t-il que la vogsphère n'est accessible que lorsqu'on est connecté au réseau scolaire?

**Comment by thumavu** [comment]
# To opt out of the system crypto-policies configuration of krb5, remove the
# symlink at /etc/krb5.conf.d/crypto-policies which will not be recreated.
includedir /etc/krb5.conf.d/

[logging]
 default = FILE:/var/log/krb5libs.log
 kdc = FILE:/var/log/krb5kdc.log
 admin_server = FILE:/var/log/kadmind.log

[libdefaults]
 dns_lookup_realm = false
 ticket_lifetime = 24h
 renew_lifetime = 7d
 forwardable = true
 rdns = false
# default_realm = EXAMPLE.COM
 default_ccache_name = KEYRING:persistent:%{uid}

[realms]
# EXAMPLE.COM = {
#  kdc = kerberos.example.com
#  admin_server = kerberos.example.com
# }

[domain_realm]
# .example.com = EXAMPLE.COM
# example.com = EXAMPLE.COM
[libdefaults]
        default_realm = 42.FR
        forwardable = true
        proxiable = true
        dns_lookup_kdc = no
        dns_lookup_realm = no
        allow_weak_crypto = true

[realms]
        42.FR = {
                kdc = kdc1.42.fr
                kdc = kdc2.42.fr
                admin_server = kdc1.42.fr
                default_domain = 42.fr
                default_lifetime = 7d
                ticket_lifetime = 7d
        }
        STAFF.42.FR = {
                kdc = dc1.staff.42.fr
                admin_server = dc1.staff.42.fr
                default_domain = staff.42.fr
        }

[domain_realm]
        .42.fr = 42.FR
        42.fr = 42.FR
        .staff.42.fr = STAFF.42.FR
        staff.42.fr = STAFF.42.FR
~

**Comment by colundrum** [comment]
Oui c'est uniquement quand tu es connecté au wifi ou réseau filaire de 42

**Comment by colundrum** [comment]
Yes, you need to be connected to 42's network (ethernet or wifi)

**Comment by thumavu** [comment]
cool thank you
