### ISSUE TITLE
Pb de au moment de kinit sur linux

### ISSUE THREAD

**Issue by CorbeauBlanc** [colundrum/42_vogsphere_access#5]
Bien le bonjour !

Juste pour signaler un petit pb que j'ai eu et que peut-être d'autres vont avoir. Je précise que j'ai eu ce pb sur un Arch Linux connecté le réseau de 42.
L'installation s'était déroulée sans encombres mais au moment de kinit je me suis fait gentiment rembarré avec une erreur du style :

> kinit: Cannot contact any KDC for realm 'Nom.De.Serveur.Bidon' while getting initial credentials.

En gros la couille c'était que root.sh écrivait la conf à la fin du fichier krb5.conf, et comme mon fichier n'était pas vide bah ça a foutu le brun et ça marchait pas.
Du coup comme j'avais rien d'important sur le fichier j'ai fait un ptit
`sudo mv /etc/krb5.conf /etc/~krb5.conf` et j'ai relancé l'install et tout a fonctionné au poil.
Wala et pour ceux qui ont des trucs importants dans krb5.conf ça doit pouvoir être modifiable à mon avis mais là j'en sais pas plus ;)

**Comment by colundrum** [comment]
Hello,
Erreur de ma part donc je vais ajouter un mv du fichier original.
Thx
